<?xml version="1.0" encoding="utf-8"?><Database Name="MCDatabase" Class="MCDataClassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\MCDatabase.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="MediCare.Properties.Settings" SettingsPropertyName="MCDatabaseConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Consultation" Member="Consultation">
    <Type Name="Consultation">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="diagnostic" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="cheminCertificat" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="cheminLettreOrientation" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="cheminScanner" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="cheminBilan" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="Consultation_Traitement" Member="Traitement" ThisKey="Id" OtherKey="IdConsultation" Type="Traitement" />
      <Association Name="Consultation_MPConsultation" Member="MPConsultation" ThisKey="Id" OtherKey="IdConsultation" Type="MPConsultation" />
      <Association Name="Consultation_Radio" Member="Radio" ThisKey="Id" OtherKey="IdConsultation" Type="Radio" />
    </Type>
  </Table>
  <Table Name="dbo.Traitement" Member="Traitement">
    <Type Name="Traitement">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Dose" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Indication" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="IdConsultation" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Traitement_MedicamenTraitement" Member="MedicamenTraitement" ThisKey="Id" OtherKey="IdTraitement" Type="MedicamenTraitement" />
      <Association Name="Consultation_Traitement" Member="Consultation" ThisKey="IdConsultation" OtherKey="Id" Type="Consultation" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MedicamenTraitement" Member="MedicamenTraitement">
    <Type Name="MedicamenTraitement">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdMedicaments" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdTraitement" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Traitement_MedicamenTraitement" Member="Traitement" ThisKey="IdTraitement" OtherKey="Id" Type="Traitement" IsForeignKey="true" />
      <Association Name="Medicaments_MedicamenTraitement" Member="Medicaments" ThisKey="IdMedicaments" OtherKey="Id" Type="Medicaments" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Medicaments" Member="Medicaments">
    <Type Name="Medicaments">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nom" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Dosage" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Medicaments_MedicamenTraitement" Member="MedicamenTraitement" ThisKey="Id" OtherKey="IdMedicaments" Type="MedicamenTraitement" />
    </Type>
  </Table>
  <Table Name="dbo.MPConsultation" Member="MPConsultation">
    <Type Name="MPConsultation">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdConsultation" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdPatient" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdMedecin" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Consultation_MPConsultation" Member="Consultation" ThisKey="IdConsultation" OtherKey="Id" Type="Consultation" IsForeignKey="true" />
      <Association Name="Patient_MPConsultation" Member="Patient" ThisKey="IdPatient" OtherKey="Id" Type="Patient" IsForeignKey="true" />
      <Association Name="Medecin_MPConsultation" Member="Medecin" ThisKey="IdMedecin" OtherKey="Id" Type="Medecin" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MPRendezVous" Member="MPRendezVous">
    <Type Name="MPRendezVous">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdPatient" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdMedecin" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdRendezVous" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Patient_MPRendezVous" Member="Patient" ThisKey="IdPatient" OtherKey="Id" Type="Patient" IsForeignKey="true" />
      <Association Name="RendezVous_MPRendezVous" Member="RendezVous" ThisKey="IdRendezVous" OtherKey="Id" Type="RendezVous" IsForeignKey="true" />
      <Association Name="Medecin_MPRendezVous" Member="Medecin" ThisKey="IdMedecin" OtherKey="Id" Type="Medecin" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Patient" Member="Patient">
    <Type Name="Patient">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="taille" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="poids" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="groupage" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="maladie" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="etatSante" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IdPersonne" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Patient_MPConsultation" Member="MPConsultation" ThisKey="Id" OtherKey="IdPatient" Type="MPConsultation" />
      <Association Name="Patient_MPRendezVous" Member="MPRendezVous" ThisKey="Id" OtherKey="IdPatient" Type="MPRendezVous" />
      <Association Name="Personne_Patient" Member="Personne" ThisKey="IdPersonne" OtherKey="Id" Type="Personne" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Personne" Member="Personne">
    <Type Name="Personne">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nom" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="prenom" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="dateNaissance" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="adresse" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="telephone" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sexe" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Personne_Patient" Member="Patient" ThisKey="Id" OtherKey="IdPersonne" Type="Patient" />
      <Association Name="Personne_Medecin" Member="Medecin" ThisKey="Id" OtherKey="IdPersonne" Type="Medecin" />
    </Type>
  </Table>
  <Table Name="dbo.Radio" Member="Radio">
    <Type Name="Radio">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="chemin" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="IdConsultation" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Consultation_Radio" Member="Consultation" ThisKey="IdConsultation" OtherKey="Id" Type="Consultation" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RendezVous" Member="RendezVous">
    <Type Name="RendezVous">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="IdPatient" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdMedecin" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Important" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Fait" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="RendezVous_MPRendezVous" Member="MPRendezVous" ThisKey="Id" OtherKey="IdRendezVous" Type="MPRendezVous" />
    </Type>
  </Table>
  <Table Name="dbo.Medecin" Member="Medecin">
    <Type Name="Medecin">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[key]" Member="key" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="IdPersonne" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Medecin_MPConsultation" Member="MPConsultation" ThisKey="Id" OtherKey="IdMedecin" Type="MPConsultation" />
      <Association Name="Medecin_MPRendezVous" Member="MPRendezVous" ThisKey="Id" OtherKey="IdMedecin" Type="MPRendezVous" />
      <Association Name="Personne_Medecin" Member="Personne" ThisKey="IdPersonne" OtherKey="Id" Type="Personne" IsForeignKey="true" />
    </Type>
  </Table>
</Database>